import { BRIDGE_ACTIVATION_URL } from './branding.js';

export const DASHBOARD_CONNECTION_SCRIPT = `
const connectionErrors={
  tunnel_settings_invalid:()=>t("ui.check_the_tunnel_id_client_path_and_runtime_api"),
  tunnel_id_invalid:()=>t("ui.the_tunnel_id_must_start_with_tunnel_followed_by"),
  tunnel_key_invalid:()=>t("ui.no_valid_runtime_api_key_is_available_paste_a"),
  tunnel_binary_invalid:()=>t("ui.select_download_install_tunnel_client_or_enter_its_full"),
  tunnel_binary_missing:()=>t("ui.no_tunnel_client_was_found_at_the_saved_path"),
  tunnel_operation_busy:()=>t("ui.a_tunnel_operation_is_in_progress_wait_for_it"),
  tunnel_download_failed:()=>t("ui.unable_to_download_tunnel_client_check_your_internet_connection"),
  tunnel_checksum_unavailable:()=>t("ui.the_download_has_no_valid_sha_256_checksum_installation"),
  tunnel_checksum_mismatch:()=>t("ui.the_download_does_not_match_its_sha_256_checksum"),
  tunnel_extract_failed:()=>t("ui.unable_to_extract_the_client_check_write_permissions_for"),
  tunnel_secret_storage_failed:()=>t("ui.unable_to_store_the_encrypted_key_under_the_current"),
  tunnel_secure_storage_unavailable:()=>t("ui.saving_tunnel_settings_through_the_dashboard_currently_requires_windows"),
  tunnel_install_platform_unsupported:()=>t("ui.automatic_installation_currently_supports_windows_x64_arm64"),
  tunnel_admin_unavailable:()=>t("ui.tunnel_management_is_unavailable_in_this_gateway_instance_restart"),
  tunnel_operation_failed:()=>t("ui.the_operation_failed_check_the_configuration_and_try_again"),
  tunnel_stop_timeout:()=>t("ui.the_current_client_has_not_stopped_no_new_client"),
  tunnel_stop_failed:()=>t("ui.unable_to_stop_the_current_client_no_new_client"),
};
function connectionError(error){return connectionErrors[error.message]?.()||friendlyError(error.message)}
function updateConnectionStatus(o){const el=$('connection-tunnel-status');if(el){if(el.dataset)el.dataset.tunnelState=o.tunnel.state;el.textContent=tunnelStateLabel(o.tunnel.state);el.className='pill '+(o.tunnel.state==='running'?'ok':'bad')}const bridge=$('connection-widget-status');if(bridge){if(bridge.dataset)bridge.dataset.bridgeState=o.bridge;bridge.textContent=bridgeLabel(o.bridge);bridge.className='pill '+(o.bridge==='ready'?'ok':'bad')}}
async function renderConnections(){
  const [data,o]=await Promise.all([api('tunnel'),api('overview')]);
  const activation=${JSON.stringify(BRIDGE_ACTIVATION_URL)};
  $('content').innerHTML=("<div class=\\"grid\\"><section class=\\"panel\\"><div class=\\"eyebrow\\">Secure MCP tunnel</div><div class=\\"section-head\\"><h2>"+t("ui.connect_to_chatgpt")+"</h2><span id=\\"connection-tunnel-status\\" class=\\"pill\\">")+esc(tunnelStateLabel(data.status.state))+("</span></div><p class=\\"notice\\">"+t("ui.configure_a_tunnel_to_connect_the_chatgpt_plugin_to")+"</p><p class=\\"notice\\">"+t("ui.prepare_a_tunnel_id_linked_to_your_chatgpt_workspace")+"</p>")+
  ("<form id=\\"tunnel-form\\" class=\\"form\\"><div class=\\"field\\" style=\\"grid-column:1/-1\\"><label for=\\"tunnel-id\\">1. Tunnel ID</label><input id=\\"tunnel-id\\" class=\\"input\\" placeholder=\\"tunnel_…\\" required maxlength=\\"39\\" autocomplete=\\"off\\"><small>"+t("ui.create_a_tunnel_in_your_organization_and_link_it")+" <a href=\\"https://platform.openai.com/settings/organization/tunnels\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" style=\\"text-decoration:underline\\">"+t("ui.open_tunnel_settings")+"</a></small></div>")+
  '<div class="field" style="grid-column:1/-1"><label for="tunnel-key">2. Runtime API key</label><input id="tunnel-key" class="input" type="password" autocomplete="new-password" minlength="20" maxlength="16384" placeholder="'+(data.hasRuntimeKey?t("ui.stored_encrypted_leave_blank_to_keep_the_current_key"):t("ui.paste_runtime_api_key"))+("\\"><small>"+t("ui.use_a_key_with_tunnels_read_use_permissions_this")+" <a href=\\"https://platform.openai.com/settings/organization/api-keys\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" style=\\"text-decoration:underline\\">"+t("ui.open_runtime_api_keys")+"</a></small></div>")+
  ("<div class=\\"field\\" style=\\"grid-column:1/-1\\"><label for=\\"tunnel-binary\\">"+t("ui.3_local_tunnel_client")+"</label><input id=\\"tunnel-binary\\" class=\\"input\\" readonly aria-describedby=\\"tunnel-client-help\\"><button id=\\"install-tunnel-client\\" class=\\"secondary\\" type=\\"button\\">"+t("ui.download_install_tunnel_client")+"</button><small id=\\"tunnel-client-help\\">"+t("ui.download_the_client_from_the_openai_repository_verify_sha")+"</small><details><summary style=\\"cursor:pointer;min-height:44px;padding-top:12px;color:var(--muted)\\">"+t("ui.advanced_use_an_existing_client")+"</summary><label for=\\"tunnel-custom-path\\" style=\\"display:block;margin:8px 0\\">"+t("ui.full_path_to_tunnel_client_exe")+"</label><input id=\\"tunnel-custom-path\\" class=\\"input\\" placeholder=\\""+t("ui.example_drive_directory_tunnel_client_exe")+"\\"></details></div>")+
  ("<label style=\\"grid-column:1/-1\\"><input id=\\"tunnel-enabled\\" type=\\"checkbox\\">"+t("ui.enable_the_tunnel_after_saving_and_when_the_gateway")+"</label><button id=\\"save-tunnel\\" class=\\"primary\\" type=\\"submit\\">"+t("ui.save_start_tunnel")+"</button><button id=\\"test-tunnel\\" class=\\"secondary\\" type=\\"button\\">"+t("ui.test_connection")+"</button><button id=\\"stop-tunnel\\" class=\\"secondary\\" type=\\"button\\">"+t("ui.stop_tunnel")+"</button><button id=\\"start-tunnel\\" class=\\"secondary\\" type=\\"button\\">"+t("ui.start_saved_tunnel")+"</button><div id=\\"tunnel-result\\" class=\\"notice\\" role=\\"status\\" style=\\"grid-column:1/-1;margin:0\\"></div></form></section>")+
  ("<section class=\\"panel\\"><div class=\\"eyebrow\\">"+t("ui.next_steps")+"</div><h2>"+t("ui.connect_the_plugin_and_widget")+"</h2><ol class=\\"steps\\"><li><span class=\\"step-num\\">1</span><div><strong>"+t("ui.save_and_test_the_tunnel")+"</strong>"+t("ui.select_test_connection_to_confirm_client_readiness_the_running")+"</div></li><li><span class=\\"step-num\\">2</span><div><strong>"+t("ui.add_the_plugin_in_chatgpt")+"</strong>"+t("ui.enable_developer_mode_open_plugins_then_select_connection_tunnel")+"</div></li><li><span class=\\"step-num\\">3</span><div><strong>"+t("ui.open_the_widget_in_a_conversation")+"</strong>"+t("ui.open_the_link_below_select_the_plugin_and_send")+"</div></li></ol><div class=\\"row\\" style=\\"margin-top:20px\\"><span>ChatGPT widget</span><span id=\\"connection-widget-status\\" class=\\"pill\\">")+esc(bridgeLabel(o.bridge))+("</span></div><p class=\\"notice\\" style=\\"margin-top:16px\\">"+t("ui.the_connected_state_confirms_the_gateway_is_receiving_widget")+"</p><a class=\\"primary\\" href=\\"")+activation+("\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\">"+t("ui.open_bridge_in_chatgpt")+" ↗</a><p class=\\"notice\\" style=\\"margin-top:20px\\"><a href=\\"https://developers.openai.com/plugins/deploy/connect-chatgpt\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" style=\\"text-decoration:underline\\">"+t("ui.openai_documentation_connect_to_chatgpt")+"</a></p></section></div>");
  $('tunnel-id').value=data.tunnelId;$('tunnel-binary').value=data.binaryPath;$('tunnel-enabled').checked=data.enabled||!data.hasRuntimeKey;$('tunnel-key').required=!data.hasRuntimeKey;
  $('install-tunnel-client').disabled=!data.canInstall;
  $('tunnel-custom-path').oninput=()=>{$('tunnel-binary').value=$('tunnel-custom-path').value.trim()};
  let busy=false;
  async function action(work){if(busy)return;busy=true;$('tunnel-form').dataset.busy='true';const buttons=[...$('tunnel-form').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('tunnel-result').textContent=t("ui.processing");try{await work()}catch(error){$('tunnel-result').textContent=connectionError(error)}finally{busy=false;delete $('tunnel-form').dataset.busy;buttons.forEach(b=>b.disabled=false);$('install-tunnel-client').disabled=!data.canInstall}}
  $('install-tunnel-client').onclick=()=>action(async()=>{const installed=await api('tunnel/install',{method:'POST',body:'{}'});$('tunnel-binary').value=installed.binaryPath;$('tunnel-result').textContent=t("ui.installed_tunnel_client")+installed.version+t("ui.enter_the_tunnel_id_and_runtime_api_key_then")});
  $('tunnel-form').onsubmit=event=>{event.preventDefault();return action(async()=>{const payload={binaryPath:$('tunnel-binary').value.trim(),tunnelId:$('tunnel-id').value.trim(),enabled:$('tunnel-enabled').checked};const key=$('tunnel-key').value.trim();if(key)payload.runtimeApiKey=key;await api('tunnel',{method:'PUT',body:JSON.stringify(payload)});$('tunnel-key').value='';$('tunnel-key').required=false;$('tunnel-key').placeholder=t("ui.stored_encrypted_leave_blank_to_keep_the_current_key");$('tunnel-result').textContent=payload.enabled?t("ui.saved_encrypted_settings_and_started_the_tunnel_select_test"):t("ui.saved_encrypted_settings_the_tunnel_is_disabled");updateConnectionStatus(await api('overview'))})};
  $('test-tunnel').onclick=()=>action(async()=>{const result=await api('tunnel/test',{method:'POST',body:'{}'});$('tunnel-result').textContent=translatedMessage(result.message);updateConnectionStatus(await api('overview'))});
  for(const operation of ['start','stop'])$(operation+'-tunnel').onclick=()=>action(async()=>{const result=await api('tunnel/'+operation,{method:'POST',body:'{}'});$('tunnel-enabled').checked=result.enabled;$('tunnel-result').textContent=operation==='start'?t("ui.tunnel_started_select_test_connection_to_confirm_readiness"):t("ui.tunnel_stopped_the_saved_configuration_is_retained");updateConnectionStatus(await api('overview'))});
  updateConnectionStatus(o);
}
`;
