import { TOUR_RESOURCES } from './dashboard-tour-assets.js';

export const DASHBOARD_TOUR_STYLE = `
.tour-image-dialog,.tour-image-toolbar h2{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.tour-image-toolbar h2{font-weight:600;letter-spacing:-.2px}
.tour-image-dialog{width:min(1000px,calc(100vw - 24px));max-width:calc(100vw - 24px);max-height:calc(100dvh - 24px);padding:0;border:1px solid var(--border);border-radius:12px;background:var(--surface);color:var(--text);overflow:auto;box-shadow:0 24px 80px #0008;overscroll-behavior:contain}.tour-image-dialog::backdrop{background:#000b;backdrop-filter:blur(4px)}.tour-image-toolbar{position:sticky;top:0;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;background:var(--surface);border-bottom:1px solid var(--border);z-index:1}.tour-image-toolbar h2{font-size:15px;margin:0}.tour-image-toolbar button{min-width:44px;min-height:44px}.tour-image-dialog figure{margin:0;padding:16px}.tour-image-dialog img{display:block;width:auto;max-width:100%;max-height:calc(100dvh - 200px);height:auto;object-fit:contain;margin:auto;border-radius:6px}.tour-image-dialog figcaption{margin:12px auto 0;font-size:13px;line-height:1.7;color:var(--muted);max-width:720px}.tour-figure a{cursor:zoom-in}
.tour-resources{display:grid;gap:8px;margin:16px 0}.tour-resource-link{display:block;padding:10px 12px;border:1px solid var(--border);border-radius:8px;background:var(--field);line-height:1.5}.tour-figure{margin:18px 0}.tour-figure a{display:block;border:1px solid var(--border);border-radius:8px;overflow:hidden}.tour-figure img{display:block;width:100%;height:auto;background:#202123}.tour-figure figcaption{font-size:12px;line-height:1.6;margin-top:8px}.tour-media-hint{font-size:12px}.tour-card{overscroll-behavior:contain;scrollbar-gutter:stable}.tour-resource-link:focus-visible,.tour-figure a:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.tour-layer{position:fixed;inset:0;z-index:70;pointer-events:none}.tour-shade{position:fixed;background:#0009;pointer-events:auto}.tour-ring{position:fixed;border:2px solid var(--accent);border-radius:10px;box-shadow:0 0 0 4px #91dfc230;pointer-events:none}.tour-card{position:fixed;z-index:80;width:min(400px,calc(100vw - 32px));max-height:calc(100dvh - 32px);overflow:auto;background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:12px;padding:24px;box-shadow:0 20px 70px #0005;pointer-events:auto}.tour-card h2{font-size:18px;letter-spacing:-.3px;font-weight:600;margin:10px 0}.tour-body{font-size:13px;color:var(--muted);line-height:1.75;overflow-wrap:anywhere}.tour-body p{margin:0 0 12px}.tour-body strong{color:var(--text);font-weight:550}.tour-body code{font-size:12px;color:var(--text);background:var(--field);padding:2px 5px;border-radius:4px}.tour-body ol,.tour-body ul{padding-left:20px;margin:0 0 12px}.tour-body li{margin-bottom:8px}.tour-body a{color:var(--accent);text-decoration:underline;text-underline-offset:3px}.tour-body pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--field);border:1px solid var(--border);border-radius:6px;padding:12px;font-size:11px}.tour-meta{display:flex;justify-content:space-between;align-items:center;font-size:11px;color:var(--muted)}.tour-progress{height:3px;background:var(--border);border-radius:3px;margin-top:16px}.tour-progress span{display:block;height:100%;background:var(--accent);border-radius:3px}.tour-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:20px}.tour-secondary-actions{display:flex;gap:16px;justify-content:space-between;margin-top:14px}.tour-text-button{border:0;background:transparent;color:var(--muted);padding:6px 0;min-height:44px;font-size:12px}.tour-text-button:hover{color:var(--text)}.tour-check{margin-top:12px;font-size:12px;color:var(--muted);border-top:1px solid var(--border);padding-top:12px}.tour-check.ok{color:var(--accent)}.tour-launcher{display:inline-flex;gap:8px;align-items:center}.tour-launcher svg{width:18px;height:18px}@media(max-width:768px){.tour-card{padding:20px;max-height:65dvh}.tour-card h2{font-size:17px}.tour-actions .primary,.tour-actions .secondary{padding:10px 12px}.tour-meta{font-size:11px}}`;

export const DASHBOARD_TOUR_SCRIPT = `
const dashboardTour=(()=>{
  const resources=${JSON.stringify(TOUR_RESOURCES)};
  function fillBody(step){
    const body=$('tour-body');body.innerHTML=step.body();const media=resources[step.id];if(!media)return;
    body.querySelectorAll('[data-tour-link]').forEach(link=>{const item=media.links[Number(link.dataset.tourLink)];if(!item)return;link.href=item.href;link.target='_blank';link.rel='noopener noreferrer'});
    if(media.images.length){for(const item of media.images){const figure=document.createElement('figure');figure.className='tour-figure';const link=document.createElement('a');link.href='/dashboard/assets/guide/'+item.file;link.addEventListener('click',event=>{event.preventDefault();viewImage(link,item)});link.setAttribute('aria-label',t('tour.images.expand',{name:t(item.caption)}));const img=document.createElement('img');img.src=link.href;img.alt=t(item.caption);img.addEventListener('load',scheduleLayout,{once:true});const caption=document.createElement('figcaption');caption.textContent=t(item.caption);const hint=document.createElement('p');hint.className='tour-media-hint';hint.textContent=t('tour.images.hint');link.append(img);figure.append(link,caption,hint);const instruction=body.querySelectorAll('ol > li')[item.instruction];(instruction||body).append(figure)}}
  }
  const key='coworkerapi.onboarding.v1';
  const steps=[
    {id:'welcome',page:'overview',target:'.nav',title:()=>t("ui.set_up_coworkerapi"),body:()=>t("tour.welcome.body")},
    {id:'tunnel',page:'connections',target:'#connection-tunnel-status',title:()=>t("ui.check_the_tunnel"),check:'tunnel',body:()=>t("tour.tunnel.body")},
    {id:'tunnel-setup',page:'connections',target:'#tunnel-form',title:()=>t("ui.configure_the_tunnel"),body:()=>t("tour.tunnel-setup.body")},
    {id:'plugin',page:'overview',target:'#bridge-detail',title:()=>t("ui.add_the_plugin_to_chatgpt"),body:()=>t("tour.plugin.body")},
    {id:'activate',page:'overview',target:'#content a.primary',title:()=>t("ui.activate_the_bridge"),body:()=>t("tour.activate.body")},
    {id:'connection',page:'overview',target:'#bridge-detail',title:()=>t("ui.verify_the_widget_connection"),check:'bridge',body:()=>t("tour.connection.body")},
    {id:'key',page:'keys',target:'#key-form',title:()=>t("ui.create_an_api_key"),body:()=>t("tour.key.body")},
    {id:'cli',page:'settings',target:'#content .panel',title:()=>t("ui.configure_your_cli"),body:()=>t("tour.cli.body")},
    {id:'models',page:'models',target:'#model-list',title:()=>t("ui.choose_a_model"),body:()=>t("tour.models.body")},
    {id:'usage',page:'usage',target:'#content .panel',title:()=>t("ui.test_a_cli_request"),body:()=>t("tour.usage.body")},
    {id:'limits',page:'limits',target:'#limits-form',title:()=>t("ui.set_request_limits"),body:()=>t("tour.limits.body")},
    {id:'finish',page:'overview',target:'#content .grid',title:()=>t("ui.verify_your_setup"),body:()=>t("tour.finish.body")}
  ];
  let state={status:'new',step:'welcome'},active=false,index=0,revision=0,lastFocus=null,frame=0;
  const layer=$('tour-layer'),card=$('tour-card');
  if(!layer||!card)return {autoStart(){},hide(){}};
  const imageDialog=$('tour-image-dialog');let imageFocus=null;
  function closeImage(){if(imageDialog?.open)imageDialog.close()}
  function viewImage(link,item){imageFocus=link;$('tour-image-title').textContent=t('tour.images.title');$('tour-image-close').textContent=t('tour.images.close');$('tour-image-full').src=link.href;$('tour-image-full').alt=t(item.caption);$('tour-image-caption').textContent=t(item.caption);imageDialog.showModal();$('tour-image-close').focus({preventScroll:true})}
  $('tour-image-close').onclick=closeImage;
  imageDialog.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();$('tour-image-close').focus({preventScroll:true})}});
  imageDialog.addEventListener('close',()=>{imageFocus?.isConnected&&imageFocus.focus({preventScroll:true});imageFocus=null});
  imageDialog.addEventListener('click',event=>{const r=imageDialog.getBoundingClientRect();if(event.target===imageDialog&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))closeImage()});
  try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&['pending','paused','dismissed','done'].includes(saved.status)&&steps.some(s=>s.id===saved.step))state=saved}catch{}
  const persist=status=>{state={status,step:steps[index].id};try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
  const clearHighlight=()=>document.querySelectorAll('.tour-current-target').forEach(el=>el.classList.remove('tour-current-target'));
  function hide(status='paused'){closeImage();revision++;active=false;persist(status);layer.classList.add('hidden');clearHighlight();if(lastFocus?.isConnected)lastFocus.focus();lastFocus=null}
  function layout(){if(!active)return;const target=document.querySelector(steps[index].target);if(target&&!target.classList.contains('tour-current-target')){clearHighlight();target.classList.add('tour-current-target')}const rect=target?.getBoundingClientRect();const vw=innerWidth,vh=innerHeight;const padding=7;
    const clamp=(value,max)=>Math.max(0,Math.min(max,value));const r=rect&&rect.width&&rect.height?{left:clamp(rect.left-padding,vw),top:clamp(rect.top-padding,vh),right:clamp(rect.right+padding,vw),bottom:clamp(rect.bottom+padding,vh)}:{left:vw/2,top:vh/2,right:vw/2,bottom:vh/2};
    const boxes=[[0,0,vw,r.top],[0,r.bottom,vw,Math.max(0,vh-r.bottom)],[0,r.top,r.left,Math.max(0,r.bottom-r.top)],[r.right,r.top,Math.max(0,vw-r.right),Math.max(0,r.bottom-r.top)]];
    document.querySelectorAll('.tour-shade').forEach((el,i)=>{const b=boxes[i];Object.assign(el.style,{left:b[0]+'px',top:b[1]+'px',width:b[2]+'px',height:b[3]+'px'})});
    const ring=$('tour-ring');Object.assign(ring.style,{left:r.left+'px',top:r.top+'px',width:Math.max(0,r.right-r.left)+'px',height:Math.max(0,r.bottom-r.top)+'px'});
    // Do not temporarily expand the card: that clamps scrollTop to zero before
    // it is shrunk again. Keep one stable cap during scroll/heartbeat updates.
    const available=Math.max(r.top-24,vh-r.bottom-24);let cap=innerWidth<=768?Math.min(vh-32,vh*.65):vh-32;if(available>=220)cap=Math.min(cap,available);const maxHeight=cap+'px';if(card.style.maxHeight!==maxHeight)card.style.maxHeight=maxHeight;
    const width=card.offsetWidth,height=card.offsetHeight;let left=Math.min(vw-width-16,Math.max(16,r.left)),top;
    if(r.bottom+height+20<=vh)top=r.bottom+14;else if(r.top-height-8>=8)top=r.top-height-8;else if(r.right+width+20<=vw){left=r.right+14;top=Math.max(16,Math.min(vh-height-16,r.top))}else{left=Math.max(16,(vw-width)/2);top=Math.max(16,vh-height-16)}
    Object.assign(card.style,{left:left+'px',top:Math.max(16,Math.min(vh-height-16,top))+'px'});
  }
  function scheduleLayout(){if(frame||!active)return;frame=requestAnimationFrame(()=>{frame=0;layout()})}
  async function show(){const token=++revision;active=true;persist('pending');clearHighlight();layer.classList.add('hidden');const step=steps[index];page=step.page;
    document.querySelectorAll('[data-page]').forEach(el=>{const chosen=el.dataset.page===page;el.classList.toggle('active',chosen);if(chosen)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});
    await render();if(token!==revision||!active)return;
    $('tour-step').textContent=t('tour.progress',{current:index+1,total:steps.length});$('tour-title').textContent=step.title();fillBody(step);card.scrollTop=0;$('tour-back').disabled=index===0;$('tour-next').textContent=index===steps.length-1?t("ui.finish_guide"):t("ui.next");$('tour-progress-bar').style.width=((index+1)/steps.length*100)+'%';$('tour-check').className='tour-check hidden';
    const target=document.querySelector(step.target);if(target){target.classList.add('tour-current-target');target.scrollIntoView({block:innerWidth<=768?'start':'center',behavior:'instant'})}
    layer.classList.remove('hidden');layout();$('tour-next').focus({preventScroll:true});refreshCheck();
  }
  function refreshCheck(){if(!active||!steps[index].check)return;const kind=steps[index].check;const el=kind==='bridge'?$('bridge-detail'):($('connection-tunnel-status')||$('tunnel-detail'));const okay=kind==='bridge'?el?.dataset.bridgeState==='ready':el?.dataset.tunnelState==='running';$('tour-check').className='tour-check '+(okay?'ok':'');$('tour-check').textContent=okay?(kind==='bridge'?t("ui.the_widget_is_connected_to_the_gateway"):t("ui.the_tunnel_process_is_running")):(kind==='bridge'?t("ui.no_heartbeat_received_check_the_widget_in_your_chatgpt"):t("ui.the_tunnel_process_is_not_running_continue_to_the"));scheduleLayout()}
  function start(){lastFocus=document.activeElement;index=['done','dismissed'].includes(state.status)?0:Math.max(0,steps.findIndex(s=>s.id===state.step));show().catch(()=>hide())}
  $('show-tour').onclick=start;$('tour-hide').onclick=()=>hide();$('tour-skip').onclick=()=>hide('dismissed');$('tour-back').onclick=()=>{if(index>0){index--;show().catch(()=>hide())}};$('tour-next').onclick=()=>{if(index===steps.length-1){hide('done');notify(t("ui.guide_progress_saved"))}else{index++;show().catch(()=>hide())}};
  document.addEventListener('keydown',event=>{if(!active||imageDialog?.open)return;if(event.key==='Escape'){event.preventDefault();hide();return}if(event.key!=='Tab')return;const target=document.querySelector(steps[index].target);const selectors='button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),[tabindex="0"]';const controls=[...card.querySelectorAll(selectors),...(target?.matches(selectors)?[target]:[]),...(target?.querySelectorAll(selectors)||[])].filter(el=>el.getClientRects().length);const current=controls.indexOf(document.activeElement);if(current===-1||(!event.shiftKey&&current===controls.length-1)||(event.shiftKey&&current===0)){event.preventDefault();controls[event.shiftKey?controls.length-1:0]?.focus()}});
  window.addEventListener('resize',scheduleLayout);window.addEventListener('scroll',scheduleLayout,true);if(typeof ResizeObserver!=='undefined')new ResizeObserver(scheduleLayout).observe(card);if(typeof MutationObserver!=='undefined')new MutationObserver(scheduleLayout).observe($('content'),{childList:true,subtree:true});
  return {isActive:()=>active,relocalize(){if(!active)return;const step=steps[index];$('tour-title').textContent=step.title();fillBody(step);$('tour-step').textContent=t('tour.progress',{current:index+1,total:steps.length});$('tour-next').textContent=index===steps.length-1?t("ui.finish_guide"):t("ui.next");refreshCheck();scheduleLayout()},autoStart(){if(!active&&(state.status==='new'||state.status==='pending'))start()},hide,refreshCheck};
})();
`;

export const DASHBOARD_TOUR_SHELL = `<div id="tour-layer" class="tour-layer hidden"><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div id="tour-ring" class="tour-ring"></div><section id="tour-card" class="tour-card" role="dialog" aria-modal="false" aria-labelledby="tour-title" aria-describedby="tour-body"><div class="tour-meta"><span><span data-i18n="ui.setup_guide_2">HƯỚNG DẪN THIẾT LẬP</span></span><span id="tour-step"></span></div><div class="tour-progress"><span id="tour-progress-bar"></span></div><h2 id="tour-title"></h2><div id="tour-body" class="tour-body"></div><div id="tour-check" class="tour-check hidden" role="status"></div><div class="tour-actions"><button id="tour-back" class="secondary"><span data-i18n="ui.back">Quay lại</span></button><button id="tour-next" class="primary"><span data-i18n="ui.next">Tiếp theo</span></button></div><div class="tour-secondary-actions"><button id="tour-skip" class="tour-text-button"><span data-i18n="ui.skip_guide">Bỏ qua hướng dẫn</span></button><button id="tour-hide" class="tour-text-button"><span data-i18n="ui.hide_for_now">Ẩn tạm</span></button></div></section></div><dialog id="tour-image-dialog" class="tour-image-dialog" aria-labelledby="tour-image-title" aria-describedby="tour-image-caption"><div class="tour-image-toolbar"><h2 id="tour-image-title"></h2><button id="tour-image-close" class="secondary" type="button"></button></div><figure><img id="tour-image-full" alt=""><figcaption id="tour-image-caption"></figcaption></figure></dialog>`;
